name: Run Lint
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            **/poetry.lock
            **/pyproject.toml
            **/*.py
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.12'
      - name: Install uv
        if: steps.changed-files.outputs.any_changed == 'true'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd integration_tests
          ~/.cargo/bin/uv sync
      - name: Run flake8
        if: steps.changed-files.outputs.any_changed == 'true' || failure()
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'lint-python'
          path: 'integration_tests'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}