name: Run Lint
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            **/poetry.lock
            **/pyproject.toml
            **/*.py
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files.outputs.any_changed == 'true'
      - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f # v12
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          name: mantrachain-e2e
      - run: nix-shell -I nixpkgs=./nix -p test-env --run "make lint-py"
        if: steps.changed-files.outputs.any_changed == 'true'